[tool.black]
line-length = 79
target-version = ['py39']

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
balanced_wrapping = true
line_length = 79
lines_between_types = 1

[flake8]
max-line-length = 79
extend-ignore = ["E203", "E501", "B008"]
